/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Dri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DriResponseDto"][];
                        "application/json": components["schemas"]["DriResponseDto"][];
                        "text/json": components["schemas"]["DriResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Ingredient"][];
                        "application/json": components["schemas"]["Ingredient"][];
                        "text/json": components["schemas"]["Ingredient"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngredientCreateDto"];
                    "text/json": components["schemas"]["IngredientCreateDto"];
                    "application/*+json": components["schemas"]["IngredientCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Ingredient"];
                        "application/json": components["schemas"]["Ingredient"];
                        "text/json": components["schemas"]["Ingredient"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Ingredient"];
                        "application/json": components["schemas"]["Ingredient"];
                        "text/json": components["schemas"]["Ingredient"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealResponseDto"][];
                        "application/json": components["schemas"]["MealResponseDto"][];
                        "text/json": components["schemas"]["MealResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MealCreateDto"];
                    "text/json": components["schemas"]["MealCreateDto"];
                    "application/*+json": components["schemas"]["MealCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealResponseDto"];
                        "application/json": components["schemas"]["MealResponseDto"];
                        "text/json": components["schemas"]["MealResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealResponseDto"];
                        "application/json": components["schemas"]["MealResponseDto"];
                        "text/json": components["schemas"]["MealResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DriResponseDto: {
            /** Format: double */
            recommended?: null | number | string;
            /** Format: double */
            upperLimit?: null | number | string;
            name?: string;
            unit?: string;
        };
        Ingredient: {
            /** Format: int32 */
            id?: number | string;
            /** Format: double */
            energy?: number | string;
            name?: string;
            /** Format: double */
            price?: number | string;
            /** Format: double */
            quantity?: number | string;
            macro?: components["schemas"]["Macro"];
            mineral?: components["schemas"]["Mineral"];
            vitamin?: components["schemas"]["Vitamin"];
        };
        IngredientCreateDto: {
            /** Format: double */
            carbohydrate?: number | string;
            /** Format: double */
            energy?: number | string;
            /** Format: double */
            fat?: number | string;
            /** Format: double */
            fiber?: number | string;
            /** Format: double */
            price?: number | string;
            /** Format: double */
            protein?: number | string;
            /** Format: double */
            quantity?: number | string;
            /** Format: double */
            salt?: number | string;
            /** Format: double */
            saturatedFat?: number | string;
            /** Format: double */
            sugar?: number | string;
            /** Format: int32 */
            usdaId?: null | number | string;
            name: string;
        };
        Macro: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            ingredientId?: number | string;
            /** Format: double */
            carbohydrate?: number | string;
            /** Format: double */
            fat?: number | string;
            /** Format: double */
            fiber?: number | string;
            /** Format: double */
            protein?: number | string;
            /** Format: double */
            saturatedFat?: number | string;
            /** Format: double */
            sugar?: number | string;
            /** Format: double */
            alphaLinolenicAcid?: null | number | string;
            /** Format: double */
            linoleicAcid?: null | number | string;
        };
        MealCreateDto: {
            /** Format: int32 */
            servings?: number | string;
            mealIngredients?: components["schemas"]["MealIngredientCreate"][];
            name: string;
        };
        MealIngredientCreate: {
            /** Format: double */
            quantityUsed?: number | string;
            /** Format: int32 */
            ingredientId?: number | string;
        };
        MealIngredientResponse: {
            /** Format: double */
            quantityUsed?: number | string;
            ingredient?: components["schemas"]["Ingredient"];
        };
        MealResponseDto: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            servings?: number | string;
            mealIngredients?: components["schemas"]["MealIngredientResponse"][];
            nutrients?: components["schemas"]["NutrientDto"];
            name?: string;
        };
        Mineral: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            ingredientId?: number | string;
            /** Format: double */
            chloride?: number | string;
            /** Format: double */
            sodium?: number | string;
            /** Format: double */
            calcium?: null | number | string;
            /** Format: double */
            chromium?: null | number | string;
            /** Format: double */
            copper?: null | number | string;
            /** Format: double */
            fluoride?: null | number | string;
            /** Format: double */
            iodine?: null | number | string;
            /** Format: double */
            iron?: null | number | string;
            /** Format: double */
            magnesium?: null | number | string;
            /** Format: double */
            manganese?: null | number | string;
            /** Format: double */
            molybdenum?: null | number | string;
            /** Format: double */
            phosphorus?: null | number | string;
            /** Format: double */
            potassium?: null | number | string;
            /** Format: double */
            selenium?: null | number | string;
            /** Format: double */
            zinc?: null | number | string;
        };
        NutrientDto: {
            /** Format: double */
            carbohydrate?: number | string;
            /** Format: double */
            energy?: number | string;
            /** Format: double */
            fat?: number | string;
            /** Format: double */
            fiber?: number | string;
            /** Format: double */
            protein?: number | string;
            /** Format: double */
            saturatedFat?: number | string;
            /** Format: double */
            sugar?: number | string;
            /** Format: double */
            alphaLinolenicAcid?: null | number | string;
            /** Format: double */
            linoleicAcid?: null | number | string;
            /** Format: double */
            chloride?: number | string;
            /** Format: double */
            sodium?: number | string;
            /** Format: double */
            calcium?: null | number | string;
            /** Format: double */
            chromium?: null | number | string;
            /** Format: double */
            copper?: null | number | string;
            /** Format: double */
            fluoride?: null | number | string;
            /** Format: double */
            iodine?: null | number | string;
            /** Format: double */
            iron?: null | number | string;
            /** Format: double */
            magnesium?: null | number | string;
            /** Format: double */
            manganese?: null | number | string;
            /** Format: double */
            molybdenum?: null | number | string;
            /** Format: double */
            phosphorus?: null | number | string;
            /** Format: double */
            potassium?: null | number | string;
            /** Format: double */
            selenium?: null | number | string;
            /** Format: double */
            zinc?: null | number | string;
            /** Format: double */
            biotin?: null | number | string;
            /** Format: double */
            choline?: null | number | string;
            /** Format: double */
            folate?: null | number | string;
            /** Format: double */
            niacin?: null | number | string;
            /** Format: double */
            pantothenicAcid?: null | number | string;
            /** Format: double */
            riboflavin?: null | number | string;
            /** Format: double */
            thiamin?: null | number | string;
            /** Format: double */
            vitaminA?: null | number | string;
            /** Format: double */
            vitaminB12?: null | number | string;
            /** Format: double */
            vitaminB6?: null | number | string;
            /** Format: double */
            vitaminC?: null | number | string;
            /** Format: double */
            vitaminD?: null | number | string;
            /** Format: double */
            vitaminE?: null | number | string;
            /** Format: double */
            vitaminK?: null | number | string;
        };
        Vitamin: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            ingredientId?: number | string;
            /** Format: double */
            biotin?: null | number | string;
            /** Format: double */
            choline?: null | number | string;
            /** Format: double */
            folate?: null | number | string;
            /** Format: double */
            niacin?: null | number | string;
            /** Format: double */
            pantothenicAcid?: null | number | string;
            /** Format: double */
            riboflavin?: null | number | string;
            /** Format: double */
            thiamin?: null | number | string;
            /** Format: double */
            vitaminA?: null | number | string;
            /** Format: double */
            vitaminB12?: null | number | string;
            /** Format: double */
            vitaminB6?: null | number | string;
            /** Format: double */
            vitaminC?: null | number | string;
            /** Format: double */
            vitaminD?: null | number | string;
            /** Format: double */
            vitaminE?: null | number | string;
            /** Format: double */
            vitaminK?: null | number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
